spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/spring-api-starter?createDatabaseIfNotExist=true
    username: root
    password: mysql
  jpa:
    show-sql: true